### ISSUE TITLE
ページを開こうとするとServer Error 

### ISSUE THREAD

**Issue by ao-spirogyra** [Code-for-SAKE/Sakepedia-Nuxt#55]
[![Image from Gyazo](https://i.gyazo.com/0bcd5ec121c1ac81e9ac0d159952be2a.png)](https://gyazo.com/0bcd5ec121c1ac81e9ac0d159952be2a)
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

https://sakepedia.code4sake.org/breweries や https://sakepedia.code4sake.org/sakes に直接飛ぼうとすると起きる
https://sakepedia.code4sake.org や http://localhost:3030/breweries や http://localhost:3030/sakes では再現しない

**Comment by nichesuch** [comment]
@ao-spirogyra 
サーバのログを確認しました。

https://sakepedia.code4sake.org/brands

```

0|npm  |  ERROR  Object.fromEntries is not a function
0|npm  |   at getList (lib/ApiClient/getList.js:16:0)
0|npm  |   at asyncData (pages/brands/index.vue:73:0)
0|npm  |   at promisify (dist/utils.js:289:0)
0|npm  |   at Promise.all.Components.map.Component (dist/server.js:256:0)
0|npm  |   at Array.map (<anonymous>)
0|npm  |   at module.exports.__webpack_exports__.default (dist/server.js:251:0)
0|npm  |   at process._tickCallback (internal/process/next_tick.js:68:7)
0|npm  | (node:1283) UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function
0|npm  |     at getList (lib/ApiClient/getList.js:16:0)
0|npm  |     at asyncData (pages/brands/index.vue:73:0)
0|npm  |     at promisify (dist/utils.js:289:0)
0|npm  |     at Promise.all.Components.map.Component (dist/server.js:256:0)
0|npm  |     at Array.map (<anonymous>)
0|npm  |     at module.exports.__webpack_exports__.default (dist/server.js:251:0)
0|npm  |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|npm  | (node:1283) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by reject ing a promise which was not handled with .catch(). (rejection id: 80)

```

これで原因分かりますか？

**Comment by ao-spirogyra** [comment]
わかりました！ありがとうございます！
